version: "2.1"

services:

  test-lisp-unit:
    image: sawtooth-dev-python:$ISOLATION_ID
    volumes:
      - $SAWTOOTH_CORE:/project/sawtooth-core
    command: nose2-3
        -c /project/sawtooth-core/families/lisp/nose2.cfg
        -v
        -s /project/sawtooth-core/families/lisp/lisp_test
    environment:
        PYTHONPATH: "/project/sawtooth-core/rest_api:\
            /project/sawtooth-core/sdk/python"
